title: "Lorenz MandelBrot"
description: "HFT Market Making"
remote_theme: b2a3e8/jekyll-theme-console

# Site settings
url: "https://lorenzmandelbrot.github.io"
baseurl: ""  # Keep this empty for a user/organization site

# Theme settings
style: dark
header_pages:
  - index.md
  - archive.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Comments (using Giscus - GitHub Discussions based)
comments:
  giscus:
    repo: "lorenzmandelbrot/lorenzmandelbrot.github.io"
    repo-id: "R_kgDONpUgBw"
    category: "Blog Comments"
    category-id: "DIC_kwDONpUgB84Cl9Ea"
    mapping: "pathname"
    theme: "dark"
    reactions-enabled: 1
    emit-metadata: 0
    input-position: "bottom"

# Syntax highlighting (Rouge is default, but you can set a theme if you want)
highlighter: rouge