title: "Lorenz MandelBrot"
description: "HFT Market Making"

remote_theme: b2a3e8/jekyll-theme-console

# GitHub Pages site settings
url: "https://lorenzmandelbrot.github.io"
baseurl: ""

# Theme settings
style: dark  # ensures dark console style
header_pages:
  - index.md
  - archive.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Kramdown + Syntax highlighting
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true
highlighter: rouge

# Comments (using Giscus - GitHub Discussions based)
comments:
  giscus:
    repo: "lorenzmandelbrot/lorenzmandelbrot.github.io"
    repo-id: "R_kgDONpUgBw"
    category: "Blog Comments"
    category-id: "DIC_kwDONpUgB84Cl9Ea"
    mapping: "pathname"
    theme: "dark"
    reactions-enabled: 1
    emit-metadata: 0
    input-position: "bottom"